---
- hosts: all
  gather_facts: false
  tasks:
  - name: Cloning repo
    ansible.builtin.git:
      repo: https://github.com/bedoshi/nginx_react_boot.git
      dest: ~/dev
  - name: Installing node packages
    npm:
      path: "~/dev/frontend"
      state: present
  - name: Build frontend app
    command: npm run build
    args:
      chdir: "~/dev/frontend"
  - name: Deploy forntend app
    become: yes
    copy:
      src: ~/dev/frontend/build
      dest: /usr/share/nginx/
  - name: Restart nginx
    become: yes
    systemd: name=nginx.service state=restarted
  - name: Build serverside app
    command: ./gradlew build
    args:
      chdir: "~/dev/serverside"
  - name: Run serverside app
    command: java -jar demo-0.0.1-SNAPSHOT.jar &
    args:
      chdir: "~/dev/serverside/build/libs"


