---
- hosts: all
  gather_facts: false
  tasks:
  - name: Cloning repo
    ansible.builtin.git:
      repo: https://github.com/bedoshi/nginx_react_boot.git
      dest: /home/ansible/dev
  - name: Installing node packages
    npm:
      path: "~/dev/frontend"
      state: present
  - name: Build app
    command: npm run build
    args:
      chdir: "~/dev/frontend"
