---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Copy repo file to install nginx
    copy:
      src: ./files/nginx.repo
      dest: /etc/yum.repos.d/nginx.repo
      mode: 0755
  - name: Install nginx
    dnf:
      name: nginx
      state: latest
  - name: Copy nginx config
    copy:
      src: ./files/my_nginx.conf
      dest: /etc/nginx/conf.d/my_nginx.conf
      mode: 0755
  - name: Enable nginx service
    systemd: name=nginx.service enabled=yes
